site_name: Api specifications
site_url: https://maxleroy.github.io

plugins:
  - search

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: 'assets/images/logo.svg'
  favicon: 'assets/images/favicon.png'
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight

nav:
  - 'Home': 'index.md'
  - 'Content negotiation': 'content-negotiation.md'
  - 'Document structure': 'document-structure.md'
  - 'Fetching data': 'fetching-data.md'
  - 'CRUD resources': 'crud.md'
  - 'Query parameters': 'query-parameters.md'
  - 'Errors': 'errors.md'
